Fix C++17 std::string_view compatibility with JsonCpp
Applied Json::StaticString wrapper to all Json::Value literal string accesses
to prevent C++17 automatic conversion to std::string_view, which JsonCpp doesn't support.

Fixed files:
- WebClient.cpp: Wrapped all json_command, value, jsonCandidate, response, and val accesses
- MusicPlaylist.cpp: Wrapped all data and root accesses
- SpeakingClientHandshake.cpp: Wrapped all json_data accesses

This resolves linking errors related to undefined reference to
Json::Value::operator[](std::basic_string_view<char, std::char_traits<char> >)